#!/bin/sh


# ======================================================================================
# ====================================== STEP 1. =======================================
# ======================================================================================

# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
# exec git diff-index --check --cached $against --


# # ======================================================================================
# # ====================================== STEP 2. =======================================
# # ======================================================================================

# # Git Hook for SwiftLint 
# # Runs at every commit and checks for an error.
# # For the test, you can run `git commit` with an empty` commit message`

# exit 0

# export PATH=/usr/local/bin:$PATH

# LINT=$(which swiftlint)

# if [[ -e "${LINT}" ]]; then
# 	echo "SwiftLint Start..."
# 	echo $(pwd)
# else
# 	echo "SwiftLint does not exist, download from https://github.com/realm/SwiftLint"
# 	exit 1
# fi

# RESULT=$($LINT lint --quiet --config .swiftlint.yml)

# if [ "$RESULT" == '' ]; then
# 	printf "SwiftLint Finished.\n"
# else
# 	echo ""
# 	printf "SwiftLint Failed. Please check below:\n"

# 	while read -r line; do
# 		FILEPATH=$(echo $line | cut -d : -f 1)
# 		L=$(echo $line | cut -d : -f 2)
# 		C=$(echo $line | cut -d : -f 3)
# 		TYPE=$(echo $line | cut -d : -f 4 | cut -c 2-)
# 		MESSAGE=$(echo $line | cut -d : -f 5 | cut -c 2-)
# 		DESCRIPTION=$(echo $line | cut -d : -f 6 | cut -c 2-)
# 		printf "\n $TYPE\n"
# 		printf "    $FILEPATH:$L:$C\n"
# 		printf "    $MESSAGE - $DESCRIPTION\n"
# 	done <<< "$RESULT"

# 	printf "\nCOMMIT ABORTED. Please fix them before commiting.\n"

# 	exit 1
# fi