use_frameworks!

target 'Test-Automate-Release-Framework_Example' do
  pod 'Test-Automate-Release-Framework', :path => '../'

  target 'Test-Automate-Release-Framework_Tests' do
    inherit! :search_paths

    
  end

end


pre_install do |installer|
  exec 'git config core.hooksPath .githooks'
  exec 'chmod +x ../.githooks/prepare-commit-msg'
  exec 'chmod +x ../.githooks/pre-push'
  exec 'chmod +x ../.githooks/pre-commit'
  exec 'chmod +x ../.githooks/commit-msg'
end