#!/bin/sh


# ======================================================================================
# ====================================== STEP 1. =======================================
# ======================================================================================

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

echo "remote = ${remote}"
echo "url = ${url}"

while read local_ref local_oid remote_ref remote_oid
do
	echo "local_ref = ${local_ref}"
	echo "local_oid = ${local_oid}"
	echo "remote_ref = ${remote_ref}"
	echo "remote_oid = ${remote_oid}"


	develop_branch="release/*"
	current_branch="$(git rev-parse --abbrev-ref HEAD)"
	most_recent_release_tag="$(git describe --tags $(git rev-list --tags --max-count=1))"


	echo "develop_branch = ${develop_branch}"
	echo "current_branch = ${current_branch}"
	echo "most_recent_release_tag = ${most_recent_release_tag}"

	exit 1

	if test "$local_oid" = "$zero"
	then
		# Handle delete
		:
	else
		if test "$remote_oid" = "$zero"
		then
			# New branch, examine all commits
			range="$local_oid"
		else
			# Update to existing branch, examine new commits
			range="$remote_oid..$local_oid"
		fi

		# Check for WIP commit
		commit=$(git rev-list -n 1 --grep '^WIP' "$range")
		if test -n "$commit"
		then
			echo >&2 "Found WIP commit in $local_ref, not pushing"
			exit 1
		fi
	fi
done


# Check a commit into the develop|master set this to your active development branch
develop_branch="release/*"
current_branch="$(git rev-parse --abbrev-ref HEAD)"
most_recent_release_tag="$(git describe --tags $(git rev-list --tags --max-count=1))"



# ======================================================================================
# ====================================== STEP 2. =======================================
# ======================================================================================

# Prevents force-pushing to master

BRANCH=`git rev-parse --abbrev-ref HEAD`
PUSH_COMMAND=`ps -ocommand= -p $PPID`
PROTECTED_BRANCHES="^(master|develop|release/*|hotfix/*)"
FORCE_PUSH="force|delete|-f"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES && "$PUSH_COMMAND" =~ $FORCE_PUSH ]]; then
  echo "Prevented force-push to protected branch \"$BRANCH\" by pre-push hook"
  exit 1
fi

exit 0