name: Auto PR
on:
  push:
    branches:
      - bot/release/*
jobs:
  AutoPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{github.ref}}
          base: master
