name: Auto Approve

on:
  pull_request:
    branches:
      - master
      - bot/release/*

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.0.0
#         if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          # token: ${{ secrets.NGUYENVANUYN96_WORKFLOW_SECRET }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  
