name: Auto PR
on:
  # workflow_run:
  #   workflows: ["Auto Upgrade Podspec Version"]
  #   types: 
  #     - completed
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'The release branch. Ex: release/1.0.0'     
        required: true
        default: 'master'
      bot_release_branch:
        description: 'The bot release branch. Ex: bot/release/1.0.0'     
        required: true
        default: 'master'

jobs:
  AutoPR:
    runs-on: ubuntu-latest
    steps:
      # - name: Download artifact file
      #   uses: actions/download-artifact@master
      #   with:
      #     name: release_artifact
      #     path: release_branch.txt

      # - name: Read the artifact file
      #   id: read_artifact
      #   run: |
      #     value=`cat release_branch.txt`
      #     echo "::set-output name=release_branch::${value}"
      #     echo ${value}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.bot_release_branch }}
 
      # - name: Get release version only
      #   id: get-release-version
      #   run: |
      #     version=$(echo ${{ steps.read_artifact.outputs.release_branch }} | sed -e "s/refs\/heads\/release\///g")
      #     echo "::set-output name=new_release_version::${version}"
      #     echo ${version}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ github.event.inputs.bot_release_branch }}
          base: ${{ github.event.inputs.release_branch }}
