name: Auto Approve

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'The release branch. Ex: release/1.0.0'     
        required: true

  # pull_request:
  #   branches:
  #     - master
  #     - release/*
  #   types:
  #     - created

jobs:
  # auto-approve_release_branch:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # - name: 1. Get branch name of PR
  #     #   uses: andrevalentin/get-branch-name-by-pr@master
  #     #   id: pr_data
  #     #   with:
  #     #     repo-token: ${{ secrets.GITHUB_TOKEN }}
  #     #     pr-id: ${{ github.event.pull_request.number }}
        
  #     - name: 2. Print branch name for debugging
  #       run: |
  #         echo "This is PR from branch ${{ github.event.inputs.release_branch }}"
    
  #     - name: 3. Check if branch name is an `release/*`
  #       uses: uynguyen-wonderlabs/get-branch-name-github-action@master
  #       id: check-branch
  #       with:
  #         branch: ${{ github.event.inputs.release_branch }}
      
  #     - name: Auto approve release branch
  #       if: ${{ steps.check-branch.outputs.is_release_branch == 'YES' }}
  #       uses: hmarr/auto-approve-action@v2.0.0
  #       # if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
  #       with:
  #         github-token: "${{ secrets.GITHUB_TOKEN }}"
  

  auto-approve_bot_release_branch:
    runs-on: ubuntu-latest
    steps:
      # - name: 1. Get branch name of PR
      #   uses: andrevalentin/get-branch-name-by-pr@master
      #   id: pr_data
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     pr-id: ${{ github.event.pull_request.number }}
        
      # - name: 2. Print branch name for debugging
      #   run: |
      #     echo "This is PR from branch ${{ steps.pr_data.outputs.branch }}"
    
      # - name: 3. Check if branch name is an `bot/release/*`
      #   uses: uynguyen-wonderlabs/get-branch-name-github-action@master
      #   id: check-branch
      #   with:
      #     branch: ${{ steps.pr_data.outputs.branch }}
        
      - name: 2. Print debugging
        run: |
          echo "This is PR number ${{ github.events.inputs.pr_number }}"
    
      - name: Auto approve release branch
        # if: ${{ steps.check-branch.outputs.is_release_branch == 'YES' }}
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.NGUYENVANUYN96_WORKFLOW_SECRET }}
          number: 24 #"${{ github.events.inputs.pr_number }}"

        # uses: hmarr/auto-approve-action@v2.0.0
        # with:
        #   github-token: "${{ secrets.GITHUB_TOKEN }}"
  