name: Auto Merge Release PR

on:
  pull_request:
     branches:
       - master
       - bot/release/*

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge approved PR
        uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.NGUYENVANUYN96_WORKFLOW_SECRET }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          pull-request: ${{ github.event.pull_request.number }}
          dry-run: true
          
